# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support For st-proxy
LUCI_DEPENDS:=+st-proxy

include $(TOPDIR)/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
